# Am I doing this right?
flags: {}
packages:
- Range/
- Image/
- App/
- Game/
- Terminal/
- Test/
extra-deps:
- linear-1.20
- vector-0.10.12.3
- GLURaw-1.5.0.2
- GLUT-2.7.0.3
- ObjectName-1.1.0.0
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.5.0
- gloss-1.9.4.1
- gloss-raster-1.9.4.1
- gloss-rendering-1.9.3.1
- bytestring-0.10.6.0
- base64-bytestring-1.0.0.1
- JuicyPixels-3.2.6.1
- JuicyPixels-util-0.2
- concurrent-extra-0.7.0.9
- ansi-terminal-0.6.2.1
- process-1.3.0.0
- deepseq-1.4.1.2
resolver: lts-3.7
